### ISSUE TITLE
JSON internationalization

### ISSUE THREAD

**Issue by robbiemu** [lxteo/Cities-Skylines-Extended-Building-Info#3]
I did a little footwork to try to get json serialization going for the interface internationalization. take a look at this thread [how to work with json](https://www.reddit.com/r/CitiesSkylinesModding/comments/31exjj/how_to_work_with_json/) — hopefully you can get that to work?

ps> additionally, my fork has descriptions for Farms and Commercial now — I think I can promise to knock one per day off.. I should be done in less than a week

**Comment by lxteo** [comment]
Hmm, based on what they said, I think they're right that JSON is overkill for our needs. Usually translation files are kept simple so that the people working on the translation don't have to understand how file formats work. I copied your translations for the text to a simple text file, it should be working now. I think some of them are too long and getting cut off.

And awesome, now there are more descriptions and names in Portuguese than in English.

**Comment by robbiemu** [comment]
thanks :) great job on refactoring the localization stuff
~~if that text config file is working I'm kinda amazed. could you get xml working?~~ nevermind, it was just my editor's line endings that was so confusing, I think. If you haven't you should mark this as closed :+1:
